services:
  neo4j:
    image: neo4j:4.3
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - ./plugins:/plugins
      - $PWD:$PWD

  mysql:
    restart: always
    image: mysql:latest
    working_dir: "$PWD"
    volumes:
      - "./:$PWD"
      - mysql:/var/lib/mysql
    ports:
      - '0:3306'
    command: '--log-bin --binlog-format=row --binlog-row-image=full'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: akeneo_pim
      MYSQL_PASSWORD: akeneo_pim
      MYSQL_DATABASE: akeneo_pim
    cap_add:
      - SYS_NICE

volumes:
  mysql: ~
